name: Auto Release

on:
  push:
    branches:
      - main   # 跟随的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip project
        run: |
          zip -r release.zip .

      - name: Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
